### ISSUE TITLE
This doesn't spit out Pager Duty metrics near as I can tell. 

### ISSUE THREAD

**Issue by jgrig472** [atbagan/pd-exporter#1]
I'm deploying this as a docker container as outlined in the readme with a generated pagerduty API key. I've also tried building the docker container with the same outcome. All I get back is the container golang metrics and pagerduty metrics that don't match up to anything significant. Below is all I get back that's labeled pagerduty. Am I missing something in understanding how this is supposed to be setup? 
Docker run command: `docker run -e AUTH_TOKEN=my-api-key  -dp 9696:9696 pd-exporter`

# HELP pagerduty_total_business_services_metric Shows the total number of business services
# TYPE pagerduty_total_business_services_metric gauge
pagerduty_total_business_services_metric 0
# HELP pagerduty_total_services_compliant_metric Shows the number of compliant services names
# TYPE pagerduty_total_services_compliant_metric gauge
pagerduty_total_services_compliant_metric 0
# HELP pagerduty_total_services_metric The number of total services in AIpagerduty
# TYPE pagerduty_total_services_metric gauge
pagerduty_total_services_metric 1
# HELP pagerduty_total_teams_metric The number of total teams in AIpagerduty
# TYPE pagerduty_total_teams_metric gauge
pagerduty_total_teams_metric 8
# HELP pagerduty_total_users_metric The number of total users in AIpagerduty
# TYPE pagerduty_total_users_metric gauge
pagerduty_total_users_metric 8

**Comment by atbagan** [comment]
@jgrig472 
This currently only spits out high level metrics as part of an initiative at work . There are some metrics it currently returns that are not relevant to you unless you work for the same org as me. The list of metrics will continue to grow as I work on this more. The list of metrics has been added to the readme and asterisks mark metrics that are irrelevant to people unless they work for my org.  I am currently working on refactoring  to add a single flag for those work specific metrics so that they are off by default, but could be triggered if needed.  Also adding non-work specific counterparts for those where it makes sense.

As for it working, and you setting it up properly.  You were able to get it setup correctly. it looks to be returning some of those metrics.  It looks like you have 8 users, 8 teams, 1 service. These are high level and probably are not what most people are looking for. 

I'd love to keep this issue open so that you could make a list of the metrics you are expecting/wanting so that I could prioritize those.  I have my own goals and things to work on with this project, but I would rather prioritize my efforts if it can help someone use this.  If you could add that list as a comment here that would be extremely helpful as I continue to work on this. 

 There is no official roadmap, but with enough input one could be created so that people know where this is heading and what is coming.  

Thanks
atbagan

**Comment by jgrig472** [comment]
@atbagan

Thanks for writing me back. The metrics I'd be wanting to get are as follows. 

1. Team Name
2. Team Members
3. Month Schedule for who's on call.
4. Current person on call and what time frame they'll be on call for. 
5. Incidents count to measure how many incidents are in a time span being graphed showing when they alerted and for how long. 
6. Running list showing incidents and their status. 
7. Link to the Grafana metric(s) that alerted for a given incident if doing alerting with Grafana to Pagerduty. 

This may be too much, but it's what I can think of at the moment that could be of value.  

Thanks,
jgrig472

**Comment by atbagan** [comment]
@jgrig472 
Thanks for writing back. I’ll review the list and get back to you. 
atbagan

**Comment by atbagan** [comment]
Hey, I haven't forgotten about this. I'm going to be closing this in favor of creating individual issues so that I can track work being completed here [Roadmap](https://github.com/atbagan/pd-exporter/projects/1). If you want to add anything to those issues just go ahead and comment on the respective issue. I'll be adding them over the next couple days and work will start on something shortly after. Thanks
atbagan
